---
title: "Data Visualization"
author: "Victoria Cutler"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)

library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(gapminder)
library(ggExtra)
library(ggbeeswarm)

library(gapminder)

# library(sf)
```

```{r}
lizards <- read_csv(file = here::here("data_tidy", "lizards.csv"))
```

```{r}
ggplot(data = lizards) +
  geom_point(aes(x = total_length, y = weight))
```

Create a histogram of total lengths for all lizards 
```{r}
ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram(bins = 30,
                 color = "orange",
                 fill = "purple",
                 size = 0.3, # this is the size of the border line
                 linetype = "dotted") # if you were to put these within "aes" it would bring up another legend because it assumes you're mapping a variable
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(
    shape = 22, # different shapes are numbered
    color = "cyan4",
    fill = "yellow",
    size = 5, # size here aligns with shape
    alpha = 1
  )
```

mapping aesthetics based on variables:
```{r}
ggplot(data = lizards, aes(x = total_length, 
                           y = weight)) +
  geom_point(aes(color = common_name,
                 size = total_length),
             alpha = 0.5) + # we're modifying transparancy consistently, if we wanted it to vary based on variable then we'd put it in aes
  theme_light()
```

faceting to see multiple trends:
```{r}
ggplot(data = lizards, aes(x = total_length, 
                           y = weight)) +
  geom_point() +
  facet_wrap(~common_name, 
             scales = "free") # saying i dont have a need for people to compare across these panels so making the axes different based on the data. makes it easier to read but harder to compare
```

find total count of lizards 
```{r}
# using group by summarize and n: we can do it this way because this data is already tidy so only one observation per row so it's okay to sum the rows
total_lizard_count <- lizards |> 
  group_by(common_name) |> 
  summarize(
    total_count = n(),
    mean_length = mean(total_length)
    )

# if you ONLY want to count, this method is very simple:
total_lizard_count_2 <- lizards |> 
  count(common_name, site) |> 
  rename(total_count = n)
```

```{r}
ggplot(data = total_lizard_count, aes(y = common_name, x = total_count)) +
  geom_col()

# ^notice that the order for character values is alphabetical. we could set the levels manually but that's tedious and not reproducible. need to make the datatype a factor if we want to re-order using fct_reorder function:

ggplot(data = total_lizard_count, aes(y = fct_reorder(common_name, total_count), 
                                      x = total_count)) +
  geom_col()
```

synthesis examples:
```{r}
# create scatterplots faceted by species for total length vs weight. the color and shape of points should different based on species (common name) and change the theme. and make each faceted panel have flexible axis limits. 

ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name
                 #,shape = common_name #default of shape is only 6 so we'd need to give it a longer vector within that set package it has
                 )) +
  theme_classic() +
  facet_wrap(~common_name, scales = "free") +
  labs(x = "Total Length (mm)",
       y = "Weight (grams)",
       title = "Jornada Basin Lizard Sites",
       subtitle = "All lizards follow the standard length-weight relationship with Western Whiptails being largest.",
       caption = "Data: Jornada Basin LTER, CCBY")
```

